cache: yarn
language: node_js
node_js:
  - node
  - '8'
  - '6'
os:
  - linux
services:
  - docker
sudo: required
after_success:
  - docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"
  - cd packages/services && ./docker-push.sh
